name: CD

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    name: Bump application version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          fetch-depth: 0

      - name: Increment application version
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          CURRENT_VERSION=$(grep -m1 -oE 'AppVersion-[0-9]+' README.md | grep -oE '[0-9]+$')

          if [ -z "$CURRENT_VERSION" ]; then
            echo "No yet found AppVersion in README.md"
            exit 1
          fi

          NEXT_VERSION=$((CURRENT_VERSION + 1))
          TIMESTAMP=$(date -u '+%Y-%m-%d %H:%M:%S UTC')

          sed -i "0,/^[[:space:]]*AppVersion-[0-9].*$/s//AppVersion-${NEXT_VERSION} - ${TIMESTAMP}/" README.md

          git add README.md
          git commit -m "bump application version to AppVersion-${NEXT_VERSION}"
          git push origin "HEAD:${{ github.head_ref || github.ref_name }}"

  validate-prod:
    name: Validate production secret
    runs-on: self-hosted
    needs: update-readme

    steps:
      - name: Validate PROD_TOKEN
        shell: bash
        env:
          PROD_TOKEN: ${{ secrets.PROD_TOKEN }}
          LOCAL_PROD_TOKEN: ${{ env.LOCAL_PROD_TOKEN }}
        run: |
          if [ -z "$LOCAL_PROD_TOKEN" ]; then
            echo "LOCAL_PROD_TOKEN not set in the environment"
            exit 1
          fi

          if [ "$PROD_TOKEN" != "$LOCAL_PROD_TOKEN" ]; then
            echo "the production token is invalid"
            exit 1
          fi

          echo "the production token is valid"